### PR TITLE
Remove the CMAKE_C_COMPILER_WORKS hack.

### PR DESCRIPTION
**Pull request by sunfishcode**
This hack worked around some early bugs clang which are fixed now,
so we can remove it. This way, if there's a problem causing clang
to not "work", we won't silently ignore it.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Oh, when I was testing this, I wasn't clearing out /opt/wasi-sdk, so it was picking up a libclang_rt.builtins-wasm32.a from a previous build.

I'll look into switching to `-DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY` instead.

**Comment by pchickey** [comment]
Still fails for me:
```
13:33:07  [2019-04-24T20:33:07.774Z] mkdir -p build/compiler-rt
13:33:07  [2019-04-24T20:33:07.774Z] cd build/compiler-rt; cmake -G "Unix Makefiles" \
13:33:07  [2019-04-24T20:33:07.774Z] 	-DCMAKE_BUILD_TYPE=RelWithDebInfo \
13:33:07  [2019-04-24T20:33:07.774Z] 	-DCMAKE_TOOLCHAIN_FILE=/workspace/wasi-sdk/wasi-sdk.cmake \
13:33:07  [2019-04-24T20:33:07.774Z] 	-DCOMPILER_RT_BAREMETAL_BUILD=On \
13:33:07  [2019-04-24T20:33:07.774Z] 	-DCOMPILER_RT_BUILD_XRAY=OFF \
13:33:07  [2019-04-24T20:33:07.774Z] 	-DCOMPILER_RT_INCLUDE_TESTS=OFF \
13:33:07  [2019-04-24T20:33:07.774Z] 	-DCOMPILER_RT_ENABLE_IOS=OFF \
13:33:07  [2019-04-24T20:33:07.774Z] 	-DCOMPILER_RT_DEFAULT_TARGET_ONLY=On \
13:33:07  [2019-04-24T20:33:07.775Z] 	-DWASI_SDK_PREFIX=/opt/fst-wasi-sdk \
13:33:07  [2019-04-24T20:33:07.775Z] 	-DCMAKE_C_FLAGS="-O1 -fdebug-prefix-map=/workspace/wasi-sdk=wasisdk://v4.2g3ce68ef333b7" \
13:33:07  [2019-04-24T20:33:07.775Z] 	-DLLVM_CONFIG_PATH=/workspace/wasi-sdk/build/llvm/bin/llvm-config \
13:33:07  [2019-04-24T20:33:07.775Z] 	-DCOMPILER_RT_OS_DIR=wasi \
13:33:07  [2019-04-24T20:33:07.775Z] 	-DCMAKE_INSTALL_PREFIX=/opt/fst-wasi-sdk/lib/clang/8.0.0/ \
13:33:07  [2019-04-24T20:33:07.775Z] 	-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
13:33:07  [2019-04-24T20:33:07.775Z] 	/workspace/wasi-sdk/src/llvm-project/compiler-rt/lib/builtins
13:33:08  [2019-04-24T20:33:08.036Z] -- The C compiler identification is Clang 8.0.0
13:33:08  [2019-04-24T20:33:08.036Z] -- The ASM compiler identification is Clang
13:33:08  [2019-04-24T20:33:08.036Z] -- Found assembler: /opt/fst-wasi-sdk/bin/clang
13:33:08  [2019-04-24T20:33:08.037Z] System is unknown to cmake, create:
13:33:08  [2019-04-24T20:33:08.037Z] Platform/Wasm to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
13:33:08  [2019-04-24T20:33:08.037Z] -- Check for working C compiler: /opt/fst-wasi-sdk/bin/clang
13:33:08  [2019-04-24T20:33:08.037Z] System is unknown to cmake, create:
13:33:08  [2019-04-24T20:33:08.037Z] Platform/Wasm to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
13:33:08  [2019-04-24T20:33:08.298Z] -- Check for working C compiler: /opt/fst-wasi-sdk/bin/clang -- broken
13:33:08  [2019-04-24T20:33:08.298Z] CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
13:33:08  [2019-04-24T20:33:08.298Z]   The C compiler "/opt/fst-wasi-sdk/bin/clang" is not able to compile a
13:33:08  [2019-04-24T20:33:08.298Z]   simple test program.
13:33:08  [2019-04-24T20:33:08.298Z] 
13:33:08  [2019-04-24T20:33:08.299Z]   It fails with the following output:
13:33:08  [2019-04-24T20:33:08.299Z] 
13:33:08  [2019-04-24T20:33:08.299Z]    Change Dir: /workspace/wasi-sdk/build/compiler-rt/CMakeFiles/CMakeTmp
13:33:08  [2019-04-24T20:33:08.299Z] 
13:33:08  [2019-04-24T20:33:08.299Z]   
13:33:08  [2019-04-24T20:33:08.299Z] 
13:33:08  [2019-04-24T20:33:08.299Z]   Run Build Command:"/usr/bin/make" "cmTC_d2f7e/fast"
13:33:08  [2019-04-24T20:33:08.299Z] 
13:33:08  [2019-04-24T20:33:08.299Z]   make[1]: Entering directory
13:33:08  [2019-04-24T20:33:08.300Z]   '/workspace/wasi-sdk/build/compiler-rt/CMakeFiles/CMakeTmp'
13:33:08  [2019-04-24T20:33:08.300Z] 
13:33:08  [2019-04-24T20:33:08.300Z]   /usr/bin/make -f CMakeFiles/cmTC_d2f7e.dir/build.make
13:33:08  [2019-04-24T20:33:08.300Z]   CMakeFiles/cmTC_d2f7e.dir/build
13:33:08  [2019-04-24T20:33:08.300Z] 
13:33:08  [2019-04-24T20:33:08.300Z]   make[2]: Entering directory
13:33:08  [2019-04-24T20:33:08.300Z]   '/workspace/wasi-sdk/build/compiler-rt/CMakeFiles/CMakeTmp'
13:33:08  [2019-04-24T20:33:08.300Z] 
13:33:08  [2019-04-24T20:33:08.300Z]   Building C object CMakeFiles/cmTC_d2f7e.dir/testCCompiler.c.obj
13:33:08  [2019-04-24T20:33:08.301Z] 
13:33:08  [2019-04-24T20:33:08.301Z]   /opt/fst-wasi-sdk/bin/clang --target=wasm32-unknown-wasi
13:33:08  [2019-04-24T20:33:08.301Z]   --sysroot=/opt/fst-wasi-sdk/share/sysroot -O1
13:33:08  [2019-04-24T20:33:08.301Z]   -fdebug-prefix-map=/workspace/wasi-sdk=wasisdk://v4.2g3ce68ef333b7 -o
13:33:08  [2019-04-24T20:33:08.301Z]   CMakeFiles/cmTC_d2f7e.dir/testCCompiler.c.obj -c
13:33:08  [2019-04-24T20:33:08.301Z]   /workspace/wasi-sdk/build/compiler-rt/CMakeFiles/CMakeTmp/testCCompiler.c
13:33:08  [2019-04-24T20:33:08.301Z] 
13:33:08  [2019-04-24T20:33:08.301Z]   Linking C executable cmTC_d2f7e
13:33:08  [2019-04-24T20:33:08.301Z] 
13:33:08  [2019-04-24T20:33:08.302Z]   /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d2f7e.dir/link.txt
13:33:08  [2019-04-24T20:33:08.302Z]   --verbose=1
13:33:08  [2019-04-24T20:33:08.302Z] 
13:33:08  [2019-04-24T20:33:08.302Z]   /opt/fst-wasi-sdk/bin/clang --target=wasm32-unknown-wasi
13:33:08  [2019-04-24T20:33:08.302Z]   --sysroot=/opt/fst-wasi-sdk/share/sysroot -O1
13:33:08  [2019-04-24T20:33:08.302Z]   -fdebug-prefix-map=/workspace/wasi-sdk=wasisdk://v4.2g3ce68ef333b7
13:33:08  [2019-04-24T20:33:08.302Z]   -Wl,--no-threads CMakeFiles/cmTC_d2f7e.dir/testCCompiler.c.obj -o
13:33:08  [2019-04-24T20:33:08.302Z]   cmTC_d2f7e
13:33:08  [2019-04-24T20:33:08.302Z] 
13:33:08  [2019-04-24T20:33:08.303Z]   wasm-ld: error: cannot open
13:33:08  [2019-04-24T20:33:08.303Z]   /opt/fst-wasi-sdk/lib/clang/8.0.0/lib/wasi/libclang_rt.builtins-wasm32.a:
13:33:08  [2019-04-24T20:33:08.303Z]   No such file or directory
13:33:08  [2019-04-24T20:33:08.303Z] 
13:33:08  [2019-04-24T20:33:08.303Z]   clang-8: error: lld command failed with exit code 1 (use -v to see
13:33:08  [2019-04-24T20:33:08.303Z]   invocation)
13:33:08  [2019-04-24T20:33:08.303Z] 
13:33:08  [2019-04-24T20:33:08.303Z]   CMakeFiles/cmTC_d2f7e.dir/build.make:97: recipe for target 'cmTC_d2f7e'
13:33:08  [2019-04-24T20:33:08.303Z]   failed
13:33:08  [2019-04-24T20:33:08.303Z] 
13:33:08  [2019-04-24T20:33:08.304Z]   make[2]: *** [cmTC_d2f7e] Error 1
13:33:08  [2019-04-24T20:33:08.304Z] 
13:33:08  [2019-04-24T20:33:08.304Z]   make[2]: Leaving directory
13:33:08  [2019-04-24T20:33:08.304Z]   '/workspace/wasi-sdk/build/compiler-rt/CMakeFiles/CMakeTmp'
13:33:08  [2019-04-24T20:33:08.304Z] 
13:33:08  [2019-04-24T20:33:08.304Z]   Makefile:126: recipe for target 'cmTC_d2f7e/fast' failed
13:33:08  [2019-04-24T20:33:08.304Z] 
13:33:08  [2019-04-24T20:33:08.304Z]   make[1]: *** [cmTC_d2f7e/fast] Error 2
13:33:08  [2019-04-24T20:33:08.304Z] 
13:33:08  [2019-04-24T20:33:08.305Z]   make[1]: Leaving directory
13:33:08  [2019-04-24T20:33:08.305Z]   '/workspace/wasi-sdk/build/compiler-rt/CMakeFiles/CMakeTmp'
13:33:08  [2019-04-24T20:33:08.305Z] 
13:33:08  [2019-04-24T20:33:08.305Z]   
13:33:08  [2019-04-24T20:33:08.305Z] 
13:33:08  [2019-04-24T20:33:08.305Z]   
13:33:08  [2019-04-24T20:33:08.305Z] 
13:33:08  [2019-04-24T20:33:08.305Z]   CMake will not be able to correctly generate this project.
13:33:08  [2019-04-24T20:33:08.305Z] Call Stack (most recent call first):
13:33:08  [2019-04-24T20:33:08.305Z]   CMakeLists.txt:8 (project)
13:33:08  [2019-04-24T20:33:08.306Z] 
13:33:08  [2019-04-24T20:33:08.306Z] 
13:33:08  [2019-04-24T20:33:08.306Z] -- Configuring incomplete, errors occurred!
```

**Comment by sunfishcode** [comment]
Ok. Unless anyone has any other ideas here, I'll just drop trying to change this for now.

**Comment by Ericson2314** [comment]
`CMAKE_TRY_COMPILE_TARGET_TYPE` was added in 3.6, I think @pchickey is using 3.5 according to one of the paths in there.

**Comment by pchickey** [comment]
correct, the builder is using `cmake` packaged for xenial, which is 3.5.1.

I could upgrade the builder if we need to - I have 3.10 available on our private build, and could install it in the open source builder from a binary package on cmake.org if need be.

**Comment by Ericson2314** [comment]
Maybe the cmake `set(..)` can be done conditionally based on the cmake version.

**Comment by sunfishcode** [comment]
I'm considering adding cmake to wasi-sdk once [the WASI patch](https://gitlab.kitware.com/cmake/cmake/merge_requests/3261) lands, and it sounds like that would fix the issue here as well.

**Comment by daniel-dune** [comment]
> I approved too soon - the build failed in the compiler-rt target:
> 
> (As an aside, I really need to get around to setting up CI, but I have been very busy)
> 
> ```
> "/opt/wasi-sdk/bin/clang" -O2 --target=wasm32-unknown-wasi -fno-builtin -fno-trapping-math -mthread-model single --sysroot="/opt/wasi-sdk/share/sysroot" -MD -MP -o /workspace/src/wasi-sysroot/build/libc-bottom-half/mman/mman.o -c /workspace/src/wasi-sysroot/libc-bottom-half/mman/mman.c
> /opt/wasi-sdk/bin/llvm-ar crs /opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libwasi-emulated-mman.a /workspace/src/wasi-sysroot/build/libc-bottom-half/mman/mman.o
> #
> # Create empty placeholder libraries.
> #
> for name in m rt pthread crypt util xnet resolv dl c++ c++abi; do \
>     /opt/wasi-sdk/bin/llvm-ar crs "/opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/lib${name}.a"; \
> done
> #
> # Collect metadata on the sysroot and perform sanity checks.
> #
> mkdir -p "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi"
> # Collect symbol information.
> # TODO: Use llvm-nm --extern-only instead of grep. This is blocked on
> # LLVM PR40497, which is fixed in 9.0, but not in 8.0.
> /opt/wasi-sdk/bin/llvm-nm --defined-only "/opt/wasi-sdk/share/sysroot/lib/wasm32-wasi"/libc.a "/opt/wasi-sdk/share/sysroot/lib/wasm32-wasi"/*.o \
>     |grep ' [[:upper:]] ' |sed 's/.* [[:upper:]] //' |LC_COLLATE=C sort > "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi/defined-symbols.txt"
> for undef_sym in $(/opt/wasi-sdk/bin/llvm-nm --undefined-only "/opt/wasi-sdk/share/sysroot/lib/wasm32-wasi"/*.a "/opt/wasi-sdk/share/sysroot/lib/wasm32-wasi"/*.o |grep ' U ' |sed 's/.* U //' |LC_COLLATE=C sort |uniq); do \
>     grep -q '\<'$undef_sym'\>' "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi/defined-symbols.txt" || echo $undef_sym; \
> done > "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi/undefined-symbols.txt"
> grep '^_*wasi_' "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi/undefined-symbols.txt" \
>     > "/opt/wasi-sdk/share/sysroot/lib/wasm32-wasi/libc.imports"
> # Generate a test file that includes all public header files.
> cd "/opt/wasi-sdk/share/sysroot" && \
> for header in $(find include -type f -not -name mman.h |grep -v /bits/); do \
>     echo '#include <'$header'>' | sed 's/include\///' ; \
> done |LC_COLLATE=C sort >share/wasm32-wasi/include-all.c ; \
> cd - >/dev/null
> # Test that it compiles.
> "/opt/wasi-sdk/bin/clang" -O2 --target=wasm32-unknown-wasi -fno-builtin -fno-trapping-math -mthread-model single --sysroot="/opt/wasi-sdk/share/sysroot" -fsyntax-only "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi/include-all.c" -Wno-\#warnings
> # Collect all the predefined macros, except for compiler version macros
> # which we don't need to track here. For the __*_ATOMIC_*_LOCK_FREE
> # macros, squash individual compiler names to attempt, toward keeping
> # these files compiler-independent.
> # TODO: Undefine __FLOAT128__ for now since it's not in clang 8.0.
> # TODO: Filter out __FLT16_* for now, as not all versions of clang have these.
> "/opt/wasi-sdk/bin/clang" -O2 --target=wasm32-unknown-wasi -fno-builtin -fno-trapping-math -mthread-model single --sysroot="/opt/wasi-sdk/share/sysroot" "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi/include-all.c" \
>     -E -dM -Wno-\#warnings \
>     -D_ALL_SOURCE \
>     -U__llvm__ \
>     -U__clang__ \
>     -U__clang_major__ \
>     -U__clang_minor__ \
>     -U__clang_patchlevel__ \
>     -U__clang_version__ \
>     -U__GNUC__ \
>     -U__GNUC_MINOR__ \
>     -U__GNUC_PATCHLEVEL__ \
>     -U__VERSION__ \
>     -U__FLOAT128__ \
>     | sed -e 's/__[[:upper:][:digit:]]*_ATOMIC_\([[:upper:][:digit:]_]*\)_LOCK_FREE/__compiler_ATOMIC_\1_LOCK_FREE/' \
>     | grep -v '^#define __FLT16_' \
>     > "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi/predefined-macros.txt"
> #
> # The build succeeded! The generated sysroot is in /opt/wasi-sdk/share/sysroot.
> #
> make[1]: Circular /opt/wasi-sdk/share/sysroot <- check dependency dropped.
> # Check that the computed metadata matches the expected metadata.
> diff -ur "/workspace/src/wasi-sysroot/expected/wasm32-wasi" "/opt/wasi-sdk/share/sysroot/share/wasm32-wasi"
> make[1]: Leaving directory '/workspace/src/wasi-sysroot'
> touch build/wasi-sysroot.BUILT
> mkdir -p build/compiler-rt
> cd build/compiler-rt; cmake -G "Unix Makefiles" \
> 	-DCMAKE_BUILD_TYPE=RelWithDebInfo \
> 	-DCMAKE_TOOLCHAIN_FILE=/workspace/wasi-sdk.cmake \
> 	-DCOMPILER_RT_BAREMETAL_BUILD=On \
> 	-DCOMPILER_RT_BUILD_XRAY=OFF \
> 	-DCOMPILER_RT_INCLUDE_TESTS=OFF \
> 	-DCOMPILER_RT_ENABLE_IOS=OFF \
> 	-DCOMPILER_RT_DEFAULT_TARGET_ONLY=On \
> 	-DWASI_SDK_PREFIX=/opt/wasi-sdk \
> 	-DCMAKE_C_FLAGS="-O1 -fdebug-prefix-map=/workspace=wasisdk://v3.13gc00a64568645+m" \
> 	-DLLVM_CONFIG_PATH=/workspace/build/llvm/bin/llvm-config \
> 	-DCOMPILER_RT_OS_DIR=wasi \
> 	-DCMAKE_INSTALL_PREFIX=/opt/wasi-sdk/lib/clang/8.0.0/ \
> 	-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
> 	/workspace/src/llvm-project/compiler-rt/lib/builtins
> -- The C compiler identification is Clang 8.0.0
> -- The ASM compiler identification is Clang
> -- Found assembler: /opt/wasi-sdk/bin/clang
> System is unknown to cmake, create:
> Platform/Wasm to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Check for working C compiler: /opt/wasi-sdk/bin/clang
> System is unknown to cmake, create:
> Platform/Wasm to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Check for working C compiler: /opt/wasi-sdk/bin/clang -- broken
> CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
>   The C compiler "/opt/wasi-sdk/bin/clang" is not able to compile a simple
>   test program.
> 
>   It fails with the following output:
> 
>    Change Dir: /workspace/build/compiler-rt/CMakeFiles/CMakeTmp
> 
>   
> 
>   Run Build Command:"/usr/bin/make" "cmTC_74e6f/fast"
> 
>   make[1]: Entering directory
>   '/workspace/build/compiler-rt/CMakeFiles/CMakeTmp'
> 
>   /usr/bin/make -f CMakeFiles/cmTC_74e6f.dir/build.make
>   CMakeFiles/cmTC_74e6f.dir/build
> 
>   make[2]: Entering directory
>   '/workspace/build/compiler-rt/CMakeFiles/CMakeTmp'
> 
>   Building C object CMakeFiles/cmTC_74e6f.dir/testCCompiler.c.obj
> 
>   /opt/wasi-sdk/bin/clang --target=wasm32-unknown-wasi
>   --sysroot=/opt/wasi-sdk/share/sysroot -O1
>   -fdebug-prefix-map=/workspace=wasisdk://v3.13gc00a64568645+m -o
>   CMakeFiles/cmTC_74e6f.dir/testCCompiler.c.obj -c
>   /workspace/build/compiler-rt/CMakeFiles/CMakeTmp/testCCompiler.c
> 
>   Linking C executable cmTC_74e6f
> 
>   /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_74e6f.dir/link.txt
>   --verbose=1
> 
>   /opt/wasi-sdk/bin/clang --target=wasm32-unknown-wasi
>   --sysroot=/opt/wasi-sdk/share/sysroot -O1
>   -fdebug-prefix-map=/workspace=wasisdk://v3.13gc00a64568645+m
>   -Wl,--no-threads CMakeFiles/cmTC_74e6f.dir/testCCompiler.c.obj -o
>   cmTC_74e6f
> 
>   wasm-ld: error: cannot open
>   /opt/wasi-sdk/lib/clang/8.0.0/lib/wasi/libclang_rt.builtins-wasm32.a: No
>   such file or directory
> 
>   clang-8: error: lld command failed with exit code 1 (use -v to see
>   invocation)
> 
>   CMakeFiles/cmTC_74e6f.dir/build.make:97: recipe for target 'cmTC_74e6f'
>   failed
> 
>   make[2]: *** [cmTC_74e6f] Error 1
> 
>   make[2]: Leaving directory
>   '/workspace/build/compiler-rt/CMakeFiles/CMakeTmp'
> 
>   Makefile:126: recipe for target 'cmTC_74e6f/fast' failed
> 
>   make[1]: *** [cmTC_74e6f/fast] Error 2
> 
>   make[1]: Leaving directory
>   '/workspace/build/compiler-rt/CMakeFiles/CMakeTmp'
> 
>   
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/workspace/build/compiler-rt/CMakeFiles/CMakeOutput.log".
> See also "/workspace/build/compiler-rt/CMakeFiles/CMakeError.log".
> Makefile:50: recipe for target 'build/compiler-rt.BUILT' failed
> make: *** [build/compiler-rt.BUILT] Error 1
> make:true'''

**Pull request closed without merging**
